### ISSUE TITLE
In 3.6.5 the buttons are all grayed out and unclickable.

### ISSUE THREAD

**Issue by NEEO1881** [BlenderDefender/BoneWidget#4]
Hi, the most basic test I did, is it that it is not available in 3.6.5? thanks.
![2023-12-11 185449](https://github.com/BlenderDefender/BoneWidget/assets/95964302/67bf5a6e-54e8-4364-b9b7-5bbd40036f79)

**Comment by BlenderDefender** [comment]
Hi @NEEO1881, the screenshot looks like you are in object mode. Since Bone Widget works on individual bones, you need to be in Edit- or Pose-Mode. Please try that out, and reopen the issue, if it still doesn't work.

**Comment by NEEO1881** [comment]
Yes, I've used edit mode and it still doesn't work.
![2023-12-12 170322](https://github.com/BlenderDefender/BoneWidget/assets/95964302/42541aac-a46e-4961-8fb8-ace73c9e90de)

**Comment by BlenderDefender** [comment]
@NEEO1881 Alright, I've double-checked the latest release, adding widgets is actually only possible in pose mode. This is intended behaviour, because trying to allow adding widgets in edit mode adds a row of potential issues. I'll add a tooltip in the next release explaining this behaviour. I hope this resolves your issue, apologies for the inconvenience.

**Comment by NEEO1881** [comment]
Thanks so much for the tip, glad we have such an awesome widget addon, hopefully it will be available in 4.0 too. Respectable work, you can sell it I‘ll support it!

**Comment by BlenderDefender** [comment]
@NEEO1881 I'm currently working on fixing errors with newer Blender versions, to make Bone Widget fully compatible with Blender 4.0. You can check the releases tab here on GitHub every once in a while, there will be a new release as soon as I'm done.
